### ISSUE TITLE
Average SR / Average Lifetime SR

### ISSUE THREAD

**Issue by teamcoltra** [overtrack-gg/overtrack-web#16]
On the graph I think a straight line which shows what your average SR is and maybe even a third graph which shows how your total average has been affected by your recent games. I believe the current graph only shows the last 40 games (maybe I misread or am misremembering the code) so maybe an all-time tally or for database sanity the last 200+ game average. 

Maybe mean, median, and mode?

**Comment by benolot** [comment]
We should focus down on what exactly is wanted to be added. Where did you want this graph to sit? Stats page or on the game list page? Maybe even a new page?

**Comment by teamcoltra** [comment]
I think we need one big super statistics page which has everything.

**Comment by teamcoltra** [comment]
@all-contributors please add benolot for design and support

**Comment by teamcoltra** [comment]
@all-contributors please add benolot for code and design

**Comment by synap5e** [comment]
Personally I like a separate SR page and a statistics page. 
Eventually SR page could include stats on grouping efficiency, SR gained/lost per hero, while stats would let people track in-depth performance on each hero e.g. looking at how a ingame stat changes over time as they improve or comparing themselves to other player averages (maybe doing something like here's your stat compare to your rank, and compared to the rank above). 

Combining SR and stats, to me, feels like putting too much in one place and is fundamentally different information.

**Comment by benolot** [comment]
Issue superseeded by https://github.com/overtrack-gg/overtrack-web/issues/74
