### ISSUE TITLE
Decide on license

### ISSUE THREAD

**Issue by synap5e** [overtrack-gg/overtrack-web#39]
overtrack-web is currently described as `© 2017-2019, Simon Pinfold`, although it includes work from other parties. We should either switch to an open source license, or include in the contributing process a forfeit of copyright. 

I'm not at all opposed to going MIT and removing the inherent default "all rights reserved", especially since this project now has people people working on it.
Perhaps there's also an argument for GPL so in the offchance this is picked up and modified by another tracker, we would also get the modifications.

I'm interested in people's thoughts.

**Comment by synap5e** [comment]
Currently planning on going GPL-3.0, unless anyone sees potential issues with this.

**Comment by synap5e** [comment]
@benolot @teamcoltra 
Are we happy with GPL-2.0?

**Comment by teamcoltra** [comment]
:) I say we close this and go with it.

**Comment by benolot** [comment]
Let's see if he notices 😉

**Comment by synap5e** [comment]
Yeah I see these through discord notifs. Been busy on role queue stuff today.
