### ISSUE TITLE
Get Latest SR If Unknown

### ISSUE THREAD

**Issue by teamcoltra** [overtrack-gg/overtrack-web#61]
If the latest SR is unknown and a game has not been added in +/- 24 hours then your latest SR should be tested against your public profile (if enabled) pulling from OWAPI (or grabbing it ourselves). It doesn't have to be saved persistently, but at least to have a latest update when you visit the site. 

https://owapi.net/api/v3/u/TeamColtra-1589/stats

**Comment by synap5e** [comment]
I'll add this as a task in the discord
