### ISSUE TITLE
Clicking anywhere on the games list page after page load causes games refetch

### ISSUE THREAD

**Issue by synap5e** [overtrack-gg/overtrack-web#66]

**Comment by teamcoltra** [comment]
How have I never noticed this before? Interesting to note: It only does it on the first click, it doesn't keep refreshing.

**Comment by synap5e** [comment]
It was introduced in #64 (which is why I assigned @jess-sio 😛 )
It's happens because the dropdown multiselect library emits "dropdown closed" events even if the dropdown was not opened, combined with introduced change.
